/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gaodg
 */
public class Agregar_Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agregar_Usuarios
     */
    public Agregar_Usuarios() {
        initComponents();
        cargardatosbd();
    }
    
    private void cargardatosbd(){
        try {
            String user = "root";
            String url = "jdbc:mysql://localhost:3306/";
            String password = "123456";
            String bd = "practicaosvaldo";
            String con = "com.mysql.cj.jdbc.Driver";
            
            Class.forName(con);
            Connection co = DriverManager.getConnection(url+bd,user,password);
            //JOptionPane.showMessageDialog(null, "si se conecta");
            
            String query = "SELECT * FROM roles";
            Statement sql = co.createStatement();
            ResultSet datos = sql.executeQuery(query);
            while(datos.next()){
                comboTipoA.addItem(datos.getString(1));           
            }
            co.close();
            
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "no se conecto");
        } catch (SQLException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           //JOptionPane.showMessageDialog(null, "no  se conecto");
            

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTipoA = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        passwordA = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmarPasword = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Agregar Usuarios");

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel2.add(Guardar);

        jButton2.setText("Cerrar");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 150));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Ususario");
        jPanel5.add(jLabel1);

        txtUsuarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAActionPerformed(evt);
            }
        });
        txtUsuarioA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioAKeyTyped(evt);
            }
        });
        jPanel5.add(txtUsuarioA);

        jLabel2.setText("Tipo");
        jPanel5.add(jLabel2);

        comboTipoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoAActionPerformed(evt);
            }
        });
        jPanel5.add(comboTipoA);

        jLabel3.setText("Contraseña");
        jPanel5.add(jLabel3);

        passwordA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordAKeyTyped(evt);
            }
        });
        jPanel5.add(passwordA);

        jLabel4.setText("Confirmar Password");
        jPanel5.add(jLabel4);
        jPanel5.add(confirmarPasword);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if(passwordA.getText().equals(confirmarPasword.getText())){
            try {
            String user = "root";
            String url = "jdbc:mysql://localhost:3306/";
            String password = "123456";
            String bd = "practicaosvaldo";
            String con = "com.mysql.cj.jdbc.Driver";
            String u,p,cp,tipo;
            u = txtUsuarioA.getText();
            p = passwordA.getText();
                              
            tipo = (String) comboTipoA.getSelectedItem();
            
            Class.forName(con);
            Connection co = DriverManager.getConnection(url+bd,user,password);
            JOptionPane.showMessageDialog(null, "si se conecta");
            
            String query = "INSERT INTO usuarios VALUES('"+u+"','"+p+"','"+tipo+"')";
            Statement sql = co.createStatement();
            sql.execute(query);
            JOptionPane.showMessageDialog(null,"El usuario se guardo correctamente");
            co.close();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "no se conecto");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "no  se conecto2");
            

        }
        }else{
            JOptionPane.showMessageDialog(null, "contraseña no coincide");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void txtUsuarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAActionPerformed

    private void txtUsuarioAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioAKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra<=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
            || (letra==95) ){//guion

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioAKeyTyped

    private void comboTipoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoAActionPerformed

    private void passwordAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordAKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra>=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
        ){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_passwordAKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> comboTipoA;
    private javax.swing.JPasswordField confirmarPasword;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField passwordA;
    private javax.swing.JTextField txtUsuarioA;
    // End of variables declaration//GEN-END:variables
}
