/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;  
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gaodg
 */
public class EliminarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public EliminarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EliminarE = new javax.swing.JButton();
        cerrare = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordE = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAbusacra = new javax.swing.JMenu();
        mnuAbuscar = new javax.swing.JMenuItem();

        setClosable(true);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel5.setText("Eliminar Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel5)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        EliminarE.setText("Eliminar");
        EliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEActionPerformed(evt);
            }
        });
        jPanel2.add(EliminarE);

        cerrare.setText("Cerrar");
        jPanel2.add(cerrare);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 150));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Ususario");
        jPanel5.add(jLabel1);

        txtUsuarioE.setEnabled(false);
        txtUsuarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEActionPerformed(evt);
            }
        });
        txtUsuarioE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioEKeyTyped(evt);
            }
        });
        jPanel5.add(txtUsuarioE);

        jLabel2.setText("Tipo");
        jPanel5.add(jLabel2);

        txtTipoE.setEnabled(false);
        jPanel5.add(txtTipoE);

        jLabel3.setText("Contraseña");
        jPanel5.add(jLabel3);

        passwordE.setEnabled(false);
        passwordE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordEKeyTyped(evt);
            }
        });
        jPanel5.add(passwordE);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        mnuAbusacra.setText("Archivo");
        mnuAbusacra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbusacraActionPerformed(evt);
            }
        });

        mnuAbuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAbuscar.setText("Buscar Usuario");
        mnuAbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbuscarActionPerformed(evt);
            }
        });
        mnuAbusacra.add(mnuAbuscar);

        jMenuBar1.add(mnuAbusacra);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEActionPerformed
        
            try {
                String user = "root";
                String url = "jdbc:mysql://localhost:3306/";
                String password = "123456";
                String bd = "practicaosvaldo";
                String con = "com.mysql.cj.jdbc.Driver";
                String u,p,cp,tipo;
                u = txtUsuarioE.getText();

                Class.forName(con);
                Connection co = DriverManager.getConnection(url+bd,user,password);
                //JOptionPane.showMessageDialog(null, "si se conecta");

                String query = "DELETE FROM usuarios WHERE usuarios='"+u+"'";
                Statement sql = co.createStatement();
                sql.execute(query);
                JOptionPane.showMessageDialog(null,"El usuario se Elimino correctamente");

                co.close();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "no se conecto");
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "no  se conecto2");

            }
       
    }//GEN-LAST:event_EliminarEActionPerformed

    private void txtUsuarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEActionPerformed

    private void txtUsuarioEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioEKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra<=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
            || (letra==95) ){//guion

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioEKeyTyped

    private void passwordEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordEKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra>=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
        ){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_passwordEKeyTyped

    private void mnuAbusacraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbusacraActionPerformed
        // TODO add your handling code here:
        
        String Us = JOptionPane.showInputDialog("Escribe el usuario a eliminar");
        if(Us.isEmpty()){
            JOptionPane.showMessageDialog(null,"no se escribe el usuario a eliminar");
        }else{
        try {
            String user = "root";
            String url = "jdbc:mysql://localhost:3306/";
            String password = "123456";
            String bd = "practicaosvaldo";
            String con = "com.mysql.cj.jdbc.Driver";
            String u,p,cp,tipo;
            u = txtUsuarioE.getText();
            
            Class.forName(con);
            Connection co = DriverManager.getConnection(url+bd,user,password);
            //JOptionPane.showMessageDialog(null, "si se conecta");
            
            String query = "SELECT * FROM usuarios WHERE usuarios='"+Us+"'";
            Statement sql = co.createStatement();
            ResultSet datos = sql.executeQuery(query);
            if(datos.next()){
                txtUsuarioE.setText(datos.getString(2));
                passwordE.setText(datos.getString(3));
                txtTipoE.setText(datos.getString(4));
                EliminarE.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null,"El usuario no exixte");
            }
            co.close();
            
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "no se conecto");
        } catch (SQLException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           //JOptionPane.showMessageDialog(null, "no  se conecto");
            

        }
        }
    }//GEN-LAST:event_mnuAbusacraActionPerformed

    private void mnuAbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbuscarActionPerformed
        // TODO add your handling code here:
        String us= JOptionPane.showInputDialog("Escribe el usuario a Eliminar");
       if (us.isEmpty()){
           JOptionPane.showMessageDialog(null, "No se escribio el usuario a eliminar");
       }else{
        try {
            String user = "root";
            String url = "jdbc:mysql://localhost:3306/";
            String password = "123456";
            String bd = "practicaosvaldo";
            String con = "com.mysql.cj.jdbc.Driver";
            
            Class.forName(con);
            Connection co = DriverManager.getConnection(url+bd,user,password);
            //JOptionPane.showMessageDialog(null, "Si se conecto");
             String query = "SELECT * FROM usuarios WHERE usuarios='"+us+"'";
             Statement sql = co.createStatement();
             ResultSet datos = sql.executeQuery(query);
             if(datos.next()){
                 txtUsuarioE.setText(datos.getString(1));
                 passwordE.setText(datos.getString(2));
                 txtTipoE.setText(datos.getString(3));
                 EliminarE.setEnabled(true);
              // comboTipo.addItem(datos.getString(2));
             }else{
                JOptionPane.showMessageDialog(null, "El usuario no existe");
             }
             /*datos.close();
             sql.close();*/
            co.close();
            
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se conecto1");
        } catch (SQLException ex) {
            //Logger.getLogger(EliminarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null, "No se conecto2");
        }
       } 
    }//GEN-LAST:event_mnuAbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarE;
    private javax.swing.JButton cerrare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu mnuAbusacra;
    private javax.swing.JMenuItem mnuAbuscar;
    private javax.swing.JPasswordField passwordE;
    private javax.swing.JTextField txtTipoE;
    private javax.swing.JTextField txtUsuarioE;
    // End of variables declaration//GEN-END:variables
}
