/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import javax.swing.JFrame;

/**
 *
 * @author gaodg
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuAAgregar = new javax.swing.JMenuItem();
        mnuAeliminar = new javax.swing.JMenuItem();
        mnuAModificar = new javax.swing.JMenuItem();
        mnuASalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        mnuEUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        mnuAAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAAgregar.setMnemonic('o');
        mnuAAgregar.setText("Agregar Usuario");
        mnuAAgregar.setEnabled(false);
        mnuAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAAgregarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAAgregar);

        mnuAeliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAeliminar.setMnemonic('s');
        mnuAeliminar.setText("Eliminar Usuario");
        mnuAeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAeliminarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAeliminar);

        mnuAModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAModificar.setMnemonic('a');
        mnuAModificar.setText("Modificar Ususario");
        mnuAModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAModificarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAModificar);

        mnuASalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuASalir.setMnemonic('x');
        mnuASalir.setText("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuASalir);

        menu.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");
        editMenu.setEnabled(false);

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menu.add(editMenu);

        mnuEUsuario.setText("Estado");

        jMenuItem1.setText("Usuario");
        mnuEUsuario.add(jMenuItem1);

        menu.add(mnuEUsuario);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuASalirActionPerformed

    private void mnuAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAAgregarActionPerformed
        // TODO add your handling code here:
        Agregar_Usuarios au = new Agregar_Usuarios();
        Escritorio.add(au);
        au.setVisible(true);        
    }//GEN-LAST:event_mnuAAgregarActionPerformed

    private void mnuAeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAeliminarActionPerformed
        // TODO add your handling code here:
        EliminarUsuario eu = new EliminarUsuario();
        Escritorio.add(eu);
        eu.setVisible(true);
    }//GEN-LAST:event_mnuAeliminarActionPerformed

    private void mnuAModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAModificarActionPerformed
        // TODO add your handling code here:
        ModicarUsuario mod = new ModicarUsuario();
        Escritorio.add(mod);
        mod.setVisible(true);
    }//GEN-LAST:event_mnuAModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menu;
    public javax.swing.JMenuItem mnuAAgregar;
    public javax.swing.JMenuItem mnuAModificar;
    private javax.swing.JMenuItem mnuASalir;
    public javax.swing.JMenuItem mnuAeliminar;
    private javax.swing.JMenu mnuEUsuario;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
