/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;  
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gaodg
 */
public class ModicarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public ModicarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ModificarM = new javax.swing.JButton();
        cerrare = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordM = new javax.swing.JPasswordField();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuAbusacra1 = new javax.swing.JMenu();
        mnuAbuscar1 = new javax.swing.JMenuItem();

        setClosable(true);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel5.setText("Modificar Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel5)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        ModificarM.setText("Modificar");
        ModificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMActionPerformed(evt);
            }
        });
        jPanel2.add(ModificarM);

        cerrare.setText("Cerrar");
        jPanel2.add(cerrare);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 150));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Ususario");
        jPanel5.add(jLabel1);

        txtUsuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioMActionPerformed(evt);
            }
        });
        txtUsuarioM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioMKeyTyped(evt);
            }
        });
        jPanel5.add(txtUsuarioM);

        jLabel2.setText("Tipo");
        jPanel5.add(jLabel2);
        jPanel5.add(txtTipoM);

        jLabel3.setText("Contraseña");
        jPanel5.add(jLabel3);

        passwordM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordMKeyTyped(evt);
            }
        });
        jPanel5.add(passwordM);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        mnuAbusacra1.setText("Archivo");
        mnuAbusacra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbusacra1ActionPerformed(evt);
            }
        });

        mnuAbuscar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAbuscar1.setText("Buscar Usuario");
        mnuAbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbuscar1ActionPerformed(evt);
            }
        });
        mnuAbusacra1.add(mnuAbuscar1);

        jMenuBar2.add(mnuAbusacra1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMActionPerformed
        
            try {
                String user = "root";
                String url = "jdbc:mysql://localhost:3306/";
                String password = "123456";
                String bd = "practicaosvaldo";
                String con = "com.mysql.cj.jdbc.Driver";
                String u,p,cp,tipo;
                u = txtUsuarioM.getText();
                p = passwordM.getText();
                tipo = txtTipoM.getText();

                //tipo = (String) txt.getSelectedItem();
                Class.forName(con);
                Connection co = DriverManager.getConnection(url+bd,user,password);
                //JOptionPane.showMessageDialog(null, "si se conecta");

                String query = "UPDATE usuarios SET Usuarios='"+u+"', "
                        + "Password='"+p+"', "
                        + "Rol='"+tipo+"' "
                        + " WHERE usuarios='"+u+"'";
                Statement sql=co.createStatement();
                sql.execute(query);
                JOptionPane.showMessageDialog(null, "El usuario fue Modificado");
                co.close();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "no se conecto");
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "no  se conecto2");

            }
       
    }//GEN-LAST:event_ModificarMActionPerformed

    private void txtUsuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMActionPerformed

    private void txtUsuarioMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioMKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra<=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
            || (letra==95) ){//guion

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioMKeyTyped

    private void passwordMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordMKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        //JOptionPane.showConfirmDialog(null, letra);
        if ((letra>=47 && letra<=58)//numeros
            || (letra>=97 && letra>=122)//Letras minusculas
            || (letra>=65 && letra<=90)//Letra maysucula
        ){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_passwordMKeyTyped

    private void mnuAbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbuscar1ActionPerformed
        // TODO add your handling code here:
        String us= JOptionPane.showInputDialog("Escribe el usuario a Eliminar");
        if (us.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se escribio el usuario a eliminar");
        }else{
            try {
                String user = "root";
                String url = "jdbc:mysql://localhost:3306/";
                String password = "123456";
                String bd = "practicaosvaldo";
                String con = "com.mysql.cj.jdbc.Driver";

                Class.forName(con);
                Connection co = DriverManager.getConnection(url+bd,user,password);
                //JOptionPane.showMessageDialog(null, "Si se conecto");
                String query = "SELECT * FROM usuarios WHERE usuarios='"+us+"'";
                Statement sql = co.createStatement();
                ResultSet datos = sql.executeQuery(query);
                if(datos.next()){
                    txtUsuarioM.setText(datos.getString(1));
                    passwordM.setText(datos.getString(2));
                    txtTipoM.setText(datos.getString(3));
                    ModificarM.setEnabled(true);
                    // comboTipo.addItem(datos.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                }
                /*datos.close();
                sql.close();*/
                co.close();

            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se conecto1");
            } catch (SQLException ex) {
                //Logger.getLogger(EliminarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se conecto2");
            }
        }
    }//GEN-LAST:event_mnuAbuscar1ActionPerformed

    private void mnuAbusacra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbusacra1ActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_mnuAbusacra1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarM;
    private javax.swing.JButton cerrare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu mnuAbusacra;
    private javax.swing.JMenu mnuAbusacra1;
    private javax.swing.JMenuItem mnuAbuscar;
    private javax.swing.JMenuItem mnuAbuscar1;
    private javax.swing.JPasswordField passwordM;
    private javax.swing.JTextField txtTipoM;
    private javax.swing.JTextField txtUsuarioM;
    // End of variables declaration//GEN-END:variables
}
