/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author gaodg
 */
public class Ventana extends javax.swing.JInternalFrame {
int c=0, c2=0;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btncalcular = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnmultiplicacion = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        optsuma = new javax.swing.JRadioButton();
        optresta = new javax.swing.JRadioButton();
        optmultplicacion = new javax.swing.JRadioButton();
        optdivision = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lblresultado = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciones Aritmeticas");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(394, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        btncalcular.setText("Calcular");
        btncalcular.setEnabled(false);
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        jPanel7.add(btncalcular);

        jPanel2.add(jPanel7);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel9.add(btncerrar);

        jPanel2.add(jPanel9);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        btnsuma.setText("suma");
        btnsuma.setEnabled(false);
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        jPanel3.add(btnsuma);

        btnresta.setText("resta");
        btnresta.setEnabled(false);
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        jPanel3.add(btnresta);

        btnmultiplicacion.setText("multiplicacion");
        btnmultiplicacion.setEnabled(false);
        btnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnmultiplicacion);

        btndivision.setText("division");
        btndivision.setEnabled(false);
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });
        jPanel3.add(btndivision);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(optsuma);
        optsuma.setSelected(true);
        optsuma.setText("suma");
        optsuma.setEnabled(false);
        optsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optsumaActionPerformed(evt);
            }
        });
        jPanel4.add(optsuma);

        buttonGroup1.add(optresta);
        optresta.setText("resta");
        optresta.setEnabled(false);
        jPanel4.add(optresta);

        buttonGroup1.add(optmultplicacion);
        optmultplicacion.setText("multiplicacion");
        optmultplicacion.setEnabled(false);
        optmultplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmultplicacionActionPerformed(evt);
            }
        });
        jPanel4.add(optmultplicacion);

        buttonGroup1.add(optdivision);
        optdivision.setText("division");
        optdivision.setEnabled(false);
        jPanel4.add(optdivision);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10);

        txtNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1ActionPerformed(evt);
            }
        });
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero1KeyTyped(evt);
            }
        });
        jPanel5.add(txtNumero1);

        txtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero2ActionPerformed(evt);
            }
        });
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero2KeyTyped(evt);
            }
        });
        jPanel5.add(txtNumero2);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        lblresultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblresultado.setText("0.0");
        jPanel11.add(lblresultado);

        jPanel5.add(jPanel11);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optmultplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmultplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optmultplicacionActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
        String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a - b;
               lblresultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a - b;
                lblresultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a - b;
                lblresultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a - t;
               lblresultado.setText(Float.toString(r));
          }
        
        }     
    }//GEN-LAST:event_btnrestaActionPerformed

    private void txtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2ActionPerformed

    private void optsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optsumaActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txtNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1ActionPerformed

    private void txtNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyTyped
         // TODO add your handling code here:
        int key = evt.getKeyChar();//convertir un char a ascii
        if ((key >= 48 && key<=57) || key==46){
             c++;
        }else{
            evt.consume();
        }
        if (key == 8){
        c--;
        }
        if (c<0){
        c = 0;
        }
        if(c>0 && c2>0){
            btnsuma.setEnabled(true);
            btnresta.setEnabled(true);
            btnmultiplicacion.setEnabled(true);
            btndivision.setEnabled(true);
            optsuma.setEnabled(true);
            optresta.setEnabled(true);
            optmultplicacion.setEnabled(true);
            optdivision.setEnabled(true);
            btncalcular.setEnabled(true);
        }else{
            btnsuma.setEnabled(false);
            btnresta.setEnabled(false);
            btnmultiplicacion.setEnabled(false);
            btndivision.setEnabled(false);
            optsuma.setEnabled(false);
            optresta.setEnabled(false);
            optmultplicacion.setEnabled(false);
            optdivision.setEnabled(false);
            btncalcular.setEnabled(false);
        }

    }//GEN-LAST:event_txtNumero1KeyTyped

    private void txtNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();//convertir un char a ascii
        if ((key >= 48 && key<=57) || key==46){
             c2++;
        }else{
            evt.consume();
        }
        if (key == 8){
            c2--;
        }
        if(c2<0){
        c2=0;
        } 
        if(c2>0 && c>0){
            btnsuma.setEnabled(true);
            btnresta.setEnabled(true);
            btnmultiplicacion.setEnabled(true);
            btndivision.setEnabled(true);
            optsuma.setEnabled(true);
            optresta.setEnabled(true);
            optmultplicacion.setEnabled(true);
            optdivision.setEnabled(true);
            btncalcular.setEnabled(true);            
        }else{
            btnsuma.setEnabled(false);
            btnresta.setEnabled(false);
            btnmultiplicacion.setEnabled(false);
            btndivision.setEnabled(false);
            optsuma.setEnabled(false);
            optresta.setEnabled(false);
            optmultplicacion.setEnabled(false);
            optdivision.setEnabled(false);
            btncalcular.setEnabled(false); 
        }
        
    }//GEN-LAST:event_txtNumero2KeyTyped

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // TODO add your handling code here:
        String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a + b;
               lblresultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a + b;
                lblresultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a + b;
                lblresultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a + t;
               lblresultado.setText(Float.toString(r));
          }
        
        }
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicacionActionPerformed
        // TODO add your handling code here:
        String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a * b;
               lblresultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a * b;
                lblresultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a * b;
                lblresultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a * t;
               lblresultado.setText(Float.toString(r));
          }
        
        }                                    
    }//GEN-LAST:event_btnmultiplicacionActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        // TODO add your handling code here:
        String n1,n2;
        n1 = txtNumero1.getText();
        n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();
        if (v.validarEnteros(n1).equals("decimal")){
           float a = Float.parseFloat(n1);
           if (v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r = a / b;
               lblresultado.setText(Float.toString(r));
           }else if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a / b;
                lblresultado.setText(Float.toString(r));
            }
        }else if (v.validarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a / b;
                lblresultado.setText(Float.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r = a / t;
               lblresultado.setText(Float.toString(r));
          }
        
        }
    }//GEN-LAST:event_btndivisionActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        String n1 = txtNumero1.getText();
        String n2 = txtNumero2.getText();
        Validaciones v=new Validaciones();                                                            
        if (optsuma.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a+b;
            lblresultado.setText(Integer.toString(c));
        }
        if (optresta.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a-b;
            lblresultado.setText(Integer.toString(c));
        }
        if (optmultplicacion.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a*b;
            lblresultado.setText(Integer.toString(c));
        }
        if (optdivision.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a/b;
            lblresultado.setText(Integer.toString(c));
        }
    }//GEN-LAST:event_btncalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnmultiplicacion;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JRadioButton optdivision;
    private javax.swing.JRadioButton optmultplicacion;
    private javax.swing.JRadioButton optresta;
    private javax.swing.JRadioButton optsuma;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
